[default]
name="colibri-node-1"
config_file="colibri.toml"
client_listen_address="127.0.0.1"
client_listen_port=8410
peer_listen_address="127.0.0.1"
peer_listen_port=8411
rate_limit_max_calls_allowed=1000
rate_limit_interval_seconds=60
run_mode="gossip"
topology=[
    "127.0.0.1:8412",
    "127.0.0.1:8413",
    "127.0.0.1:8414",
]
gossip_interval_ms=500
gossip_fanout=1
hash_replication_factor=1